// Generated by gencpp from file tanpack/BatteryRequest.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_BATTERYREQUEST_H
#define TANPACK_MESSAGE_BATTERYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tanpack
{
template <class ContainerAllocator>
struct BatteryRequest_
{
  typedef BatteryRequest_<ContainerAllocator> Type;

  BatteryRequest_()
    {
    }
  BatteryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tanpack::BatteryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tanpack::BatteryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryRequest_

typedef ::tanpack::BatteryRequest_<std::allocator<void> > BatteryRequest;

typedef boost::shared_ptr< ::tanpack::BatteryRequest > BatteryRequestPtr;
typedef boost::shared_ptr< ::tanpack::BatteryRequest const> BatteryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tanpack::BatteryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tanpack::BatteryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tanpack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tanpack::BatteryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tanpack::BatteryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tanpack::BatteryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tanpack::BatteryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tanpack::BatteryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tanpack::BatteryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tanpack::BatteryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tanpack::BatteryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tanpack::BatteryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tanpack/BatteryRequest";
  }

  static const char* value(const ::tanpack::BatteryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tanpack::BatteryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::tanpack::BatteryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tanpack::BatteryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tanpack::BatteryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tanpack::BatteryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TANPACK_MESSAGE_BATTERYREQUEST_H
