// Generated by gencpp from file tanpack/Battery.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_BATTERY_H
#define TANPACK_MESSAGE_BATTERY_H

#include <ros/service_traits.h>


#include <tanpack/BatteryRequest.h>
#include <tanpack/BatteryResponse.h>


namespace tanpack
{

struct Battery
{

typedef BatteryRequest Request;
typedef BatteryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Battery
} // namespace tanpack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tanpack::Battery > {
  static const char* value()
  {
    return "df7f08c1443b38b4ac0bbc90dbc93e28";
  }

  static const char* value(const ::tanpack::Battery&) { return value(); }
};

template<>
struct DataType< ::tanpack::Battery > {
  static const char* value()
  {
    return "tanpack/Battery";
  }

  static const char* value(const ::tanpack::Battery&) { return value(); }
};


// service_traits::MD5Sum< ::tanpack::BatteryRequest> should match
// service_traits::MD5Sum< ::tanpack::Battery >
template<>
struct MD5Sum< ::tanpack::BatteryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::Battery >::value();
  }
  static const char* value(const ::tanpack::BatteryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::BatteryRequest> should match
// service_traits::DataType< ::tanpack::Battery >
template<>
struct DataType< ::tanpack::BatteryRequest>
{
  static const char* value()
  {
    return DataType< ::tanpack::Battery >::value();
  }
  static const char* value(const ::tanpack::BatteryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tanpack::BatteryResponse> should match
// service_traits::MD5Sum< ::tanpack::Battery >
template<>
struct MD5Sum< ::tanpack::BatteryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::Battery >::value();
  }
  static const char* value(const ::tanpack::BatteryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::BatteryResponse> should match
// service_traits::DataType< ::tanpack::Battery >
template<>
struct DataType< ::tanpack::BatteryResponse>
{
  static const char* value()
  {
    return DataType< ::tanpack::Battery >::value();
  }
  static const char* value(const ::tanpack::BatteryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TANPACK_MESSAGE_BATTERY_H
