// Generated by gencpp from file tanpack/Camera.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_CAMERA_H
#define TANPACK_MESSAGE_CAMERA_H

#include <ros/service_traits.h>


#include <tanpack/CameraRequest.h>
#include <tanpack/CameraResponse.h>


namespace tanpack
{

struct Camera
{

typedef CameraRequest Request;
typedef CameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Camera
} // namespace tanpack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tanpack::Camera > {
  static const char* value()
  {
    return "a8c7a5d1cecba3ff861f52d5345675c3";
  }

  static const char* value(const ::tanpack::Camera&) { return value(); }
};

template<>
struct DataType< ::tanpack::Camera > {
  static const char* value()
  {
    return "tanpack/Camera";
  }

  static const char* value(const ::tanpack::Camera&) { return value(); }
};


// service_traits::MD5Sum< ::tanpack::CameraRequest> should match
// service_traits::MD5Sum< ::tanpack::Camera >
template<>
struct MD5Sum< ::tanpack::CameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::Camera >::value();
  }
  static const char* value(const ::tanpack::CameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::CameraRequest> should match
// service_traits::DataType< ::tanpack::Camera >
template<>
struct DataType< ::tanpack::CameraRequest>
{
  static const char* value()
  {
    return DataType< ::tanpack::Camera >::value();
  }
  static const char* value(const ::tanpack::CameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tanpack::CameraResponse> should match
// service_traits::MD5Sum< ::tanpack::Camera >
template<>
struct MD5Sum< ::tanpack::CameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::Camera >::value();
  }
  static const char* value(const ::tanpack::CameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::CameraResponse> should match
// service_traits::DataType< ::tanpack::Camera >
template<>
struct DataType< ::tanpack::CameraResponse>
{
  static const char* value()
  {
    return DataType< ::tanpack::Camera >::value();
  }
  static const char* value(const ::tanpack::CameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TANPACK_MESSAGE_CAMERA_H
