// Generated by gencpp from file tanpack/PositionCommand.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_POSITIONCOMMAND_H
#define TANPACK_MESSAGE_POSITIONCOMMAND_H

#include <ros/service_traits.h>


#include <tanpack/PositionCommandRequest.h>
#include <tanpack/PositionCommandResponse.h>


namespace tanpack
{

struct PositionCommand
{

typedef PositionCommandRequest Request;
typedef PositionCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionCommand
} // namespace tanpack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tanpack::PositionCommand > {
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::tanpack::PositionCommand&) { return value(); }
};

template<>
struct DataType< ::tanpack::PositionCommand > {
  static const char* value()
  {
    return "tanpack/PositionCommand";
  }

  static const char* value(const ::tanpack::PositionCommand&) { return value(); }
};


// service_traits::MD5Sum< ::tanpack::PositionCommandRequest> should match
// service_traits::MD5Sum< ::tanpack::PositionCommand >
template<>
struct MD5Sum< ::tanpack::PositionCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::PositionCommand >::value();
  }
  static const char* value(const ::tanpack::PositionCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::PositionCommandRequest> should match
// service_traits::DataType< ::tanpack::PositionCommand >
template<>
struct DataType< ::tanpack::PositionCommandRequest>
{
  static const char* value()
  {
    return DataType< ::tanpack::PositionCommand >::value();
  }
  static const char* value(const ::tanpack::PositionCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tanpack::PositionCommandResponse> should match
// service_traits::MD5Sum< ::tanpack::PositionCommand >
template<>
struct MD5Sum< ::tanpack::PositionCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::PositionCommand >::value();
  }
  static const char* value(const ::tanpack::PositionCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::PositionCommandResponse> should match
// service_traits::DataType< ::tanpack::PositionCommand >
template<>
struct DataType< ::tanpack::PositionCommandResponse>
{
  static const char* value()
  {
    return DataType< ::tanpack::PositionCommand >::value();
  }
  static const char* value(const ::tanpack::PositionCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TANPACK_MESSAGE_POSITIONCOMMAND_H
