// Generated by gencpp from file tanpack/PositionRequest.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_POSITIONREQUEST_H
#define TANPACK_MESSAGE_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tanpack
{
template <class ContainerAllocator>
struct PositionRequest_
{
  typedef PositionRequest_<ContainerAllocator> Type;

  PositionRequest_()
    {
    }
  PositionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tanpack::PositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tanpack::PositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionRequest_

typedef ::tanpack::PositionRequest_<std::allocator<void> > PositionRequest;

typedef boost::shared_ptr< ::tanpack::PositionRequest > PositionRequestPtr;
typedef boost::shared_ptr< ::tanpack::PositionRequest const> PositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tanpack::PositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tanpack::PositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tanpack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tanpack::PositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tanpack::PositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tanpack::PositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tanpack::PositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tanpack::PositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tanpack::PositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tanpack::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tanpack::PositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tanpack::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tanpack/PositionRequest";
  }

  static const char* value(const ::tanpack::PositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tanpack::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::tanpack::PositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tanpack::PositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tanpack::PositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tanpack::PositionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TANPACK_MESSAGE_POSITIONREQUEST_H
