// Generated by gencpp from file tanpack/PositionCommandRequest.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_POSITIONCOMMANDREQUEST_H
#define TANPACK_MESSAGE_POSITIONCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tanpack
{
template <class ContainerAllocator>
struct PositionCommandRequest_
{
  typedef PositionCommandRequest_<ContainerAllocator> Type;

  PositionCommandRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  PositionCommandRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::tanpack::PositionCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tanpack::PositionCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionCommandRequest_

typedef ::tanpack::PositionCommandRequest_<std::allocator<void> > PositionCommandRequest;

typedef boost::shared_ptr< ::tanpack::PositionCommandRequest > PositionCommandRequestPtr;
typedef boost::shared_ptr< ::tanpack::PositionCommandRequest const> PositionCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tanpack::PositionCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tanpack::PositionCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tanpack::PositionCommandRequest_<ContainerAllocator1> & lhs, const ::tanpack::PositionCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tanpack::PositionCommandRequest_<ContainerAllocator1> & lhs, const ::tanpack::PositionCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tanpack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tanpack::PositionCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tanpack::PositionCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tanpack::PositionCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::tanpack::PositionCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tanpack/PositionCommandRequest";
  }

  static const char* value(const ::tanpack::PositionCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::tanpack::PositionCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tanpack::PositionCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tanpack::PositionCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TANPACK_MESSAGE_POSITIONCOMMANDREQUEST_H
