// Generated by gencpp from file tanpack/Position.msg
// DO NOT EDIT!


#ifndef TANPACK_MESSAGE_POSITION_H
#define TANPACK_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <tanpack/PositionRequest.h>
#include <tanpack/PositionResponse.h>


namespace tanpack
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace tanpack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tanpack::Position > {
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::tanpack::Position&) { return value(); }
};

template<>
struct DataType< ::tanpack::Position > {
  static const char* value()
  {
    return "tanpack/Position";
  }

  static const char* value(const ::tanpack::Position&) { return value(); }
};


// service_traits::MD5Sum< ::tanpack::PositionRequest> should match
// service_traits::MD5Sum< ::tanpack::Position >
template<>
struct MD5Sum< ::tanpack::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::Position >::value();
  }
  static const char* value(const ::tanpack::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::PositionRequest> should match
// service_traits::DataType< ::tanpack::Position >
template<>
struct DataType< ::tanpack::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::tanpack::Position >::value();
  }
  static const char* value(const ::tanpack::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tanpack::PositionResponse> should match
// service_traits::MD5Sum< ::tanpack::Position >
template<>
struct MD5Sum< ::tanpack::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tanpack::Position >::value();
  }
  static const char* value(const ::tanpack::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tanpack::PositionResponse> should match
// service_traits::DataType< ::tanpack::Position >
template<>
struct DataType< ::tanpack::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::tanpack::Position >::value();
  }
  static const char* value(const ::tanpack::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TANPACK_MESSAGE_POSITION_H
